
import {Pelicula} from './modelos';

export const peliculas: Pelicula[] = [
    {
      titulo: "Babe el cerdito valiente",
      resumen: "Un cerdito que quiere ser perro pastor",
      genero: "Familiar",
      masVisto: true,
      calificacionImdb: 6.7,
      premioGalardon: true,
      fechaEstreno: new Date("1995-08-04"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/babe.png",
    },
    {
      titulo: "Intocable",
      resumen: "Un hombre que se queda tetrapléjico y contrata a un cuidador",
      genero: "Familiar",
      masVisto: true,
      calificacionImdb: 8.5,
      premioGalardon: true,
      fechaEstreno: new Date("2011-11-02"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/intocable.png",
    },
    {
      titulo: "The Karate Kid",
      resumen: "Un niño que aprende karate",
      genero: "Familiar",
      masVisto: true,
      calificacionImdb: 7.2,
      premioGalardon: false,
      fechaEstreno: new Date("1984-06-22"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/karate-kid.png",
    },
    {
      titulo: "Poli de Guardería",
      resumen: "Un policía que se hace pasar por profesor de guardería",
      genero: "Familiar",
      masVisto: false,
      calificacionImdb: 5.6,
      premioGalardon: false,
      fechaEstreno: new Date("1990-12-21"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/poli-guarderia.png",
    },
    {
      titulo: "El príncipe de Zamunda",
      resumen: "Un príncipe africano que se va a Nueva York a buscar esposa",
      genero: "Familiar",
      masVisto: false,
      calificacionImdb: 7,
      premioGalardon: false,
      fechaEstreno: new Date("1988-06-29"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/principe-zamunda.png",
    },
    {
      titulo: "Angry Birds",
      resumen: "Una película de los pájaros de Angry Birds",
      genero: "Animación",
      masVisto: false,
      calificacionImdb: 6.3,
      premioGalardon: false,
      fechaEstreno: new Date("2016-05-11"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/angry-birds.png",
    },
    {
      titulo: "Los Croods",
      resumen: "Una familia de cavernícolas que se encuentra con un hombre moderno",
      genero: "Animación",
      masVisto: false,
      calificacionImdb: 7.2,
      premioGalardon: false,
      fechaEstreno: new Date("2013-03-15"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/croods.png",
    },
    {
      titulo: "José, el rey de los sueños",
      resumen: "La historia de José de la Biblia",
      genero: "Animación",
      masVisto: false,
      calificacionImdb: 6.5,
      premioGalardon: false,
      fechaEstreno: new Date("2000-10-27"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/jose.png",
    },
    {
      titulo: "La patrulla canina",
      resumen: "Una película de la patrulla canina",
      genero: "Animación",
      masVisto: false,
      calificacionImdb: 4.7,
      premioGalardon: false,
      fechaEstreno: new Date("2021-08-20"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/patrulla-canina.png",
    },
    {
      titulo: "Los pitufos",
      resumen: "Una película de Los Pitufos",
      genero: "Animación",
      masVisto: false,
      calificacionImdb: 5.4,
      premioGalardon: false,
      fechaEstreno: new Date("2011-07-29"),
      imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/pitufos.png"
    },
    {
        titulo: "El cazador y la reina del hielo",
        resumen: "La historia de la reina del hielo",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 6.1,
        premioGalardon: false,
        fechaEstreno: new Date("2016-04-08"),
        imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/cazador.png",
      },
      {
        titulo: "Ghost Rider",
        resumen: "Un hombre que se convierte en un esqueleto en llamas",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.2,
        premioGalardon: false,
        fechaEstreno: new Date("2007-02-16"),
        imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/ghost-rider.png",
      },
      {
        titulo: "La momia",
        resumen: "La historia de la momia",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.2,
        premioGalardon: false,
        fechaEstreno: new Date("2008-08-01"),
        imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/momia.png",
      },
      {
        titulo: "Vampire Academy",
        resumen: "Una academia de vampiros",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 5.5,
        premioGalardon: false,
        fechaEstreno: new Date("2014-02-14"),
        imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/vampire-academy.png",
      },
      {
        titulo: "Warcraft: El origen",
        resumen: "La historia de Warcraft",
        genero: "Aventuras",
        masVisto: false,
        calificacionImdb: 6.8,
        premioGalardon: false,
        fechaEstreno: new Date("2016-06-03"),
        imagen: "https://raw.githubusercontent.com/Lemoncode/fotos-ejemplos/main/mflix/warcraft.png",
      },
    ];